### PR TITLE
Changed hardcoded http methods

### PR DESCRIPTION
**Pull request by pete911**

### CODE REVIEW

**Comment by husobee** [comment]
hello @pete911:  I am trying to run the unit tests against your fork, and am having issues. 

https://github.com/reisinger/vestigo/blob/master/router_test.go#L692
https://github.com/reisinger/vestigo/blob/master/router_test.go#L716

^^ those need to be update to reflect that we are using a map[string]bool instead of a list

When those are corrected, I notice that the main "api" test is failing here: https://github.com/reisinger/vestigo/blob/master/router_test.go#L635

I will try to help debug why that test is failing later tonight.  Thanks for your contribution!

**Comment by pete911** [comment]
hi, I have fixed those unit tests (sorry about that), but as you said there are still 2 tests failing in `router_test.go`. These are `TestParamNames` and `TestRouterAPI`. I will try to fix them.

**Comment by pete911** [comment]
ok, all the tests are passing, the problem was (mine obviously :)) that I have changed `var names []string` in `common.go:37` to `var names = make([]string, len(r.URL.Query()))`. So the slice was fixed.

**Comment by husobee** [comment]
Just FYI: Turns out that those http method consts are in a newer version of go than 1.5... updated travis to build with go1.6.3 in this PR: https://github.com/husobee/vestigo/pull/39

**Pull request merged**
